### ISSUE TITLE
No longer called google refine

### ISSUE THREAD

**Issue by bhoffnerosu** [carpentries-incubator/OpenRefine-humanities-lesson#4]
Remove "(also called GoogleRefine)" or change to "formerly called" as above.

33 > This lesson requires a working copy of OpenRefine (also called 
34 > GoogleRefine).    

Surprised to see this one is so old and has never gotten off the ground, because I could see it being quite an excellent course, and a gamechanger for many of our humanities scholars.

**Comment by iaine** [comment]
Thanks for this. I have updated it to match the set up file. 

Apropos, your question. Please do feel free to use it.
